package platform

import (
	"context"
	"errors"
	"resume-platform/internal/compat"
	"strings"
)

func (a *App) Migrate(ctx context.Context) error {
	tx, err := a.Pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	if _, err = tx.Exec(ctx, "SELECT pg_advisory_xact_lock(72460909)"); err != nil {
		return err
	}
	var exists bool
	if err = tx.QueryRow(ctx, "SELECT to_regclass('public.accounts_user') IS NOT NULL").Scan(&exists); err != nil {
		return err
	}
	if !exists {
		lines := []string{}
		for _, line := range strings.Split(compat.Schema, "\n") {
			if !strings.HasPrefix(line, "\\") && !strings.Contains(line, "pg_catalog.set_config('search_path'") {
				lines = append(lines, line)
			}
		}
		if _, err = tx.Exec(ctx, strings.Join(lines, "\n")); err != nil {
			return err
		}
	} else {
		var active int
		if err = tx.QueryRow(ctx, "SELECT count(*) FROM core_processingrun WHERE status IN ('pending','running','waiting_conflict','cancelling') AND protocol_version <> 'resume-analysis/v3'").Scan(&active); err != nil {
			return err
		}
		if active > 0 {
			return errors.New("在途旧协议任务尚未结束，请先完成或取消后升级")
		}
		_, err = tx.Exec(ctx, `CREATE TABLE IF NOT EXISTS core_resumetextextraction (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,file_sha256 varchar(64) NOT NULL,extractor_version varchar(128) NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL,CONSTRAINT resume_text_file_version_unique UNIQUE(file_sha256,extractor_version));
ALTER TABLE core_processingrunscopeitem ADD COLUMN IF NOT EXISTS processing_node varchar(32) NOT NULL DEFAULT 'pending';
ALTER TABLE core_processingrunscopeitem ADD COLUMN IF NOT EXISTS text_extraction_id bigint REFERENCES core_resumetextextraction(id) ON DELETE SET NULL;`)
		if err != nil {
			return err
		}
	}
	_, err = tx.Exec(ctx, `CREATE TABLE IF NOT EXISTS platform_go_jobs (id bigserial PRIMARY KEY,run_id bigint UNIQUE REFERENCES core_processingrun(id) ON DELETE CASCADE,status text NOT NULL DEFAULT 'pending',lease_until timestamptz,worker_token text NOT NULL DEFAULT '',attempts integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS platform_go_jobs_claim ON platform_go_jobs(status,lease_until); CREATE TABLE IF NOT EXISTS platform_go_maintenance(id bigserial PRIMARY KEY,task_id text UNIQUE NOT NULL,kind text NOT NULL,payload jsonb NOT NULL,status text NOT NULL DEFAULT 'pending',worker_token text NOT NULL DEFAULT '',lease_until timestamptz,attempts integer NOT NULL DEFAULT 0,error_code text NOT NULL DEFAULT '',created_at timestamptz NOT NULL DEFAULT now());`)
	if err != nil {
		return err
	}
	if err = a.migrateDepartmentInbox(ctx, tx); err != nil {
		return err
	}
	if err = a.migratePositionPools(ctx, tx); err != nil {
		return err
	}
	return tx.Commit(ctx)
}
func (a *App) Seed(ctx context.Context) error {
	tx, err := a.Pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)
	if _, err = tx.Exec(ctx, "SELECT pg_advisory_xact_lock(72460910)"); err != nil {
		return err
	}
	var ct int64
	err = tx.QueryRow(ctx, "INSERT INTO django_content_type(app_label,model) VALUES ('accounts','user') ON CONFLICT(app_label,model) DO UPDATE SET model=EXCLUDED.model RETURNING id").Scan(&ct)
	if err != nil {
		return err
	}
	ids := map[string]int64{}
	for _, module := range a.Spec.PermissionTree {
		for _, child := range list(module["children"]) {
			p := obj(child)
			var id int64
			err = tx.QueryRow(ctx, "INSERT INTO auth_permission(name,content_type_id,codename) VALUES($1,$2,$3) ON CONFLICT(content_type_id,codename) DO UPDATE SET name=EXCLUDED.name RETURNING id", p["name"], ct, strings.ReplaceAll(str(p["code"]), ".", "__")).Scan(&id)
			if err != nil {
				return err
			}
			ids[str(p["code"])] = id
		}
	}
	for name, codes := range a.Spec.RolePermissions {
		group, findErr := one(ctx, tx, "SELECT row_to_json(g) FROM auth_group g WHERE name=$1", name)
		if findErr == nil {
			continue
		}
		group, err = a.save(ctx, tx, "auth_group", nil, Object{"name": name})
		if err != nil {
			return err
		}
		for _, code := range codes {
			if _, err = tx.Exec(ctx, "INSERT INTO auth_group_permissions(group_id,permission_id) VALUES($1,$2) ON CONFLICT DO NOTHING", group["id"], ids[code]); err != nil {
				return err
			}
		}
	}
	user, findErr := one(ctx, tx, "SELECT row_to_json(u) FROM accounts_user u WHERE username='012358'")
	if findErr != nil {
		user, err = a.save(ctx, tx, "accounts_user", nil, Object{"username": "012358", "email": "huyue2@ueascend.com", "password": "!" + token(20), "role": "admin", "is_superuser": true, "is_staff": true, "is_active": true, "date_joined": now()})
		if err != nil {
			return err
		}
		_, err = tx.Exec(ctx, "INSERT INTO accounts_user_groups(user_id,group_id) SELECT $1,id FROM auth_group WHERE name='管理员' ON CONFLICT DO NOTHING", user["id"])
		if err != nil {
			return err
		}
	}
	if err = a.seedInitialData(ctx, tx); err != nil {
		return err
	}
	return tx.Commit(ctx)
}
func (a *App) IssueDevToken(ctx context.Context, username string) (string, error) {
	if !a.Config.Debug || oauthSettings().ready() {
		return "", errors.New("开发 Token 仅在 DEBUG 环境可用")
	}
	user, err := one(ctx, a.Pool, "SELECT row_to_json(u) FROM accounts_user u WHERE username=$1 AND is_active", username)
	if err != nil {
		return "", err
	}
	return a.sessionToken(ctx, user["id"])
}
func (a *App) sessionToken(ctx context.Context, userID any) (string, error) {
	var value string
	err := a.Pool.QueryRow(ctx, "INSERT INTO authtoken_token(key,created,user_id) VALUES($1,now(),$2) ON CONFLICT(user_id) DO UPDATE SET user_id=EXCLUDED.user_id RETURNING key", token(20), userID).Scan(&value)
	return value, err
}
