// Code generated by resume-contracts tools/build_bundle.py. DO NOT EDIT.
package contract

type AllocationPin struct {
	PinID               string `json:"pin_id"`
	KernelBuild         string `json:"kernel_build"`
	ProtocolVersion     string `json:"protocol_version"`
	ResultSchemaVersion string `json:"result_schema_version"`
	ToolsetVersion      string `json:"toolset_version"`
	PolicyVersion       string `json:"policy_version"`
	InstructionVersion  string `json:"instruction_version"`
}

type AllocationCapabilities struct {
	ProtocolVersion     string   `json:"protocol_version"`
	ResultSchemaVersion string   `json:"result_schema_version"`
	TaskKinds           []string `json:"task_kinds"`
	ExecutionModes      []string `json:"execution_modes"`
	KernelBuild         string   `json:"kernel_build"`
	ToolsetVersion      string   `json:"toolset_version"`
	PolicyVersion       string   `json:"policy_version"`
	InstructionVersion  string   `json:"instruction_version"`
	ToolNames           []string `json:"tool_names"`
	Mock                bool     `json:"mock"`
}

type AllocationTag struct {
	Code          string `json:"code"`
	Status        string `json:"status"`
	ConfidenceBPS int64  `json:"confidence_bps"`
	Source        string `json:"source"`
	AssertionRef  string `json:"assertion_ref"`
	Verified      bool   `json:"verified"`
}

type AllocationMember struct {
	MemberID              int64           `json:"member_id"`
	CandidateRef          string          `json:"candidate_ref"`
	ApplicationRef        string          `json:"application_ref"`
	QualificationRef      string          `json:"qualification_ref"`
	QualificationRevision int64           `json:"qualification_revision"`
	MemberRevision        int64           `json:"member_revision"`
	WorkflowRevision      int64           `json:"workflow_revision"`
	SourceRevision        int64           `json:"source_revision"`
	StandardRef           string          `json:"standard_ref"`
	StandardHash          string          `json:"standard_hash"`
	TagsHash              string          `json:"tags_hash"`
	Admitted              bool            `json:"admitted"`
	CreatedAt             string          `json:"created_at"`
	Tags                  []AllocationTag `json:"tags"`
	AllowedDemandIDs      []int64         `json:"allowed_demand_ids"`
	CountedDemandIDs      []int64         `json:"counted_demand_ids"`
}

type AllocationDemand struct {
	DemandID               int64    `json:"demand_id"`
	DepartmentRef          string   `json:"department_ref"`
	Revision               int64    `json:"revision"`
	ReceptionState         string   `json:"reception_state"`
	RequiredTags           []string `json:"required_tags"`
	PreferredTags          []string `json:"preferred_tags"`
	Priority               int64    `json:"priority"`
	RecentSupplyCount      int64    `json:"recent_supply_count"`
	LastAllocationSequence int64    `json:"last_allocation_sequence"`
}

type AllocationSnapshot struct {
	SnapshotID     string             `json:"snapshot_id"`
	SnapshotAt     string             `json:"snapshot_at"`
	ScopeRef       string             `json:"scope_ref"`
	EntityRef      string             `json:"entity_ref"`
	PoolRef        string             `json:"pool_ref"`
	ScopeRevision  int64              `json:"scope_revision"`
	PolicyRevision int64              `json:"policy_revision"`
	Epoch          int64              `json:"epoch"`
	NextSequence   int64              `json:"next_sequence"`
	WindowSeconds  int64              `json:"window_seconds"`
	Members        []AllocationMember `json:"members"`
	Demands        []AllocationDemand `json:"demands"`
}

type AllocationBudget struct {
	MaxDurationSeconds int64 `json:"max_duration_seconds"`
	MaxToolCalls       int64 `json:"max_tool_calls"`
}

type AllocationRequest struct {
	ProtocolVersion string             `json:"protocol_version"`
	TaskKind        string             `json:"task_kind"`
	ExecutionMode   string             `json:"execution_mode"`
	TaskID          string             `json:"task_id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	Pin             AllocationPin      `json:"pin"`
	SnapshotHash    string             `json:"snapshot_hash"`
	Snapshot        AllocationSnapshot `json:"snapshot"`
	Budget          AllocationBudget   `json:"budget"`
}

type AllocationDecision struct {
	MemberID         int64    `json:"member_id"`
	QualificationRef string   `json:"qualification_ref"`
	Action           string   `json:"action"`
	DemandID         int64    `json:"demand_id"`
	DepartmentRef    string   `json:"department_ref"`
	MatchedTags      []string `json:"matched_tags"`
	AssertionRefs    []string `json:"assertion_refs"`
	Order            []int64  `json:"order"`
	Sequence         int64    `json:"sequence"`
	ReasonCode       string   `json:"reason_code"`
}

type AllocationTrace struct {
	ToolNames     []string `json:"tool_names"`
	ToolCallCount int64    `json:"tool_call_count"`
	DurationMS    int64    `json:"duration_ms"`
	Reused        bool     `json:"reused"`
}

type AllocationResponse struct {
	ProtocolVersion     string               `json:"protocol_version"`
	ResultSchemaVersion string               `json:"result_schema_version"`
	TaskID              string               `json:"task_id"`
	IdempotencyKey      string               `json:"idempotency_key"`
	Pin                 AllocationPin        `json:"pin"`
	SnapshotHash        string               `json:"snapshot_hash"`
	TerminalState       string               `json:"terminal_state"`
	Decisions           []AllocationDecision `json:"decisions"`
	SafeTrace           AllocationTrace      `json:"safe_trace"`
}
